const authRouter = require('./authRoutes')
const settingRouter = require('./settingRoutes')
const postRouter = require('./postRoutes')
const answerRouter = require('./answerRoutes')
const adminRouter = require('./adminRoutes')
const pettyCashRouter = require('./pettyCashRoutes')
const productRouter = require('./productRoutes')
const customerRouter = require('./customerRoutes')
const orderRouter = require('./orderRoutes')
const notFound = require('./404')

module.exports = function (app) {
    app.use('/auth', authRouter)
    app.use('/setting', settingRouter)
    app.use('/petty-cash', pettyCashRouter)
    app.use('/product', productRouter)
    app.use('/customer', customerRouter)
    app.use('/order', orderRouter)
    app.use('/post', postRouter)
    app.use('/answer', answerRouter)
    app.use('/admin', adminRouter)
    app.use(notFound)
}